# Copyright 2024 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Michael Rogenmoser <michaero@iis.ee.ethz.ch>

name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-verilog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            ./src
            ./test
          exclude_paths:
          extra_args: "--rules=-interface-name-style --lint_fatal --parse_fatal"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewdog_reporter: github-check

  lint-sv-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Verible formatter action
        uses: chipsalliance/verible-formatter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files:
            ./src/*.sv
            ./test/*.sv
            ./text/synth/*.sv
          parameters:
            --flagfile .verilog_format
          fail_on_formatting_suggestions: true
